version: "3.7"

services:
    hadoop:
        image: harisekhon/hadoop:2.7
        networks: 
            - enigma
        volumes:
            - data:/dfs/data
        ports:
          - "8020:8020"
          - "8042:8042"
          - "8088:8088"
          - "19888:19888"
          - "50070:50070"
          - "50075:50075"

volumes:
    data:

networks:
    enigma:
        external: true
